FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git build-essential libmysqlclient-dev && \
    useradd -ms /bin/bash py4web

USER py4web
WORKDIR /home/py4web

# Crear y activar venv
RUN python3 -m venv /home/py4web/venv
ENV PATH="/home/py4web/venv/bin:$PATH"

RUN pip install --no-cache-dir py4web mysqlclient

COPY apps /home/py4web/apps

EXPOSE 8000

CMD ["py4web", "run", "apps", "--host", "0.0.0.0", "--port", "8000"]

