FROM ubuntu:24.04

# Dependencias
RUN apt-get update &&     apt-get install -y python3 python3-pip git &&     pip3 install --no-cache-dir py4web mysqlclient &&     useradd -ms /bin/bash py4web

USER py4web
WORKDIR /home/py4web

# Copiar apps iniciales
COPY apps /home/py4web/apps

EXPOSE 8000

CMD ["py4web", "run", "apps", "--host", "0.0.0.0", "--port", "8000"]
